use super::ThemeMethod;

#[derive(Clone)]
pub struct CommonTheme {
    pub font_family_base: String,
    pub font_color: String,
    pub background_color: String,
    pub border_color: String,
    pub color_scheme: String,

    pub color_primary: String,
    pub color_primary_hover: String,
    pub color_primary_active: String,
    pub color_success: String,
    pub color_success_hover: String,
    pub color_success_active: String,
    pub color_warning: String,
    pub color_warning_hover: String,
    pub color_warning_active: String,
    pub color_error: String,
    pub color_error_hover: String,
    pub color_error_active: String,

    pub color_neutral_background_1: String,
    pub color_neutral_background_1_hover: String,
    pub color_neutral_background_1_pressed: String,
    pub color_neutral_foreground_1: String,
    pub color_neutral_foreground_1_hover: String,
    pub color_neutral_foreground_1_pressed: String,
    pub color_neutral_foreground_2: String,
    pub color_neutral_foreground_2_hover: String,
    pub color_neutral_foreground_2_pressed: String,
    pub color_neutral_foreground_2_brand_hover: String,
    pub color_neutral_foreground_2_brand_pressed: String,
    pub color_neutral_foreground_on_brand: String,
    pub color_neutral_stroke_1: String,
    pub color_neutral_stroke_1_hover: String,
    pub color_neutral_stroke_1_pressed: String,
    pub color_brand_background: String,
    pub color_brand_background_hover: String,
    pub color_brand_background_pressed: String,
    pub color_subtle_background: String,
    pub color_subtle_background_hover: String,
    pub color_subtle_background_pressed: String,
    pub color_transparent_background: String,
    pub color_transparent_background_hover: String,
    pub color_transparent_background_pressed: String,

    pub font_size_base_300: String,

    pub line_height_base300: String,

    pub font_weight_regular: String,
    pub font_weight_semibold: String,
    pub font_weight_bold: String,

    pub stroke_width_thin: String,

    pub border_radius_medium: String,

    pub spacing_horizontal_m: String,

    pub duration_faster: String,
    pub curve_easy_ease: String,

    pub font_size: String,
    pub font_size_tiny: String,
    pub font_size_small: String,
    pub font_size_medium: String,
    pub font_size_large: String,
    pub font_size_huge: String,

    pub height_tiny: String,
    pub height_small: String,
    pub height_medium: String,
    pub height_large: String,

    pub line_height: String,
    pub line_height_small: String,
    pub line_height_medium: String,
    pub line_height_large: String,
    pub line_height_huge: String,

    pub border_radius: String,
    pub border_radius_small: String,
    pub border_radius_large: String,
}

impl CommonTheme {
    fn common() -> Self {
        Self {
            font_family_base: "'Segoe UI', 'Segoe UI Web (West European)', -apple-system, BlinkMacSystemFont, Roboto, 'Helvetica Neue', sans-serif".into(),
            font_color: "".into(),
            background_color: "".into(),
            border_color: "".into(),
            color_scheme: "".into(),
            color_primary: "".into(),
            color_primary_hover: "".into(),
            color_primary_active: "".into(),
            color_success: "".into(),
            color_success_hover: "".into(),
            color_success_active: "".into(),
            color_warning: "".into(),
            color_warning_hover: "".into(),
            color_warning_active: "".into(),
            color_error: "".into(),
            color_error_hover: "".into(),
            color_error_active: "".into(),

            color_neutral_background_1: "".into(),
            color_neutral_background_1_hover: "".into(),
            color_neutral_background_1_pressed: "".into(),
            color_neutral_foreground_1: "".into(),
            color_neutral_foreground_1_hover: "".into(),
            color_neutral_foreground_1_pressed: "".into(),
            color_neutral_foreground_2: "".into(),
            color_neutral_foreground_2_hover: "".into(),
            color_neutral_foreground_2_pressed: "".into(),
            color_neutral_foreground_2_brand_hover: "".into(),
            color_neutral_foreground_2_brand_pressed: "".into(),
            color_neutral_foreground_on_brand: "#fff".into(),
            color_neutral_stroke_1: "".into(),
            color_neutral_stroke_1_hover: "".into(),
            color_neutral_stroke_1_pressed: "".into(),
            color_brand_background: "".into(),
            color_brand_background_hover: "".into(),
            color_brand_background_pressed: "".into(),
            color_subtle_background: "transparent".into(),
            color_subtle_background_hover: "".into(),
            color_subtle_background_pressed: "".into(),
            color_transparent_background: "transparent".into(),
            color_transparent_background_hover: "transparent".into(),
            color_transparent_background_pressed: "transparent".into(),

            font_size_base_300: "14px".into(),

            line_height_base300: "20px".into(),

            font_weight_regular: "400".into(),
            font_weight_semibold: "600".into(),
            font_weight_bold: "700".into(),

            stroke_width_thin: "1px".into(),

            border_radius_medium: "4px".into(),

            spacing_horizontal_m: "12px".into(),

            duration_faster: "100ms".into(),
            curve_easy_ease: "cubic-bezier(0.33,0,0.67,1)".into(),

            font_size: "14px".into(),
            font_size_tiny: "12px".into(),
            font_size_small: "14px".into(),
            font_size_medium: "14px".into(),
            font_size_large: "15px".into(),
            font_size_huge: "16px".into(),

            height_tiny: "22px".into(),
            height_small: "28px".into(),
            height_medium: "34px".into(),
            height_large: "40px".into(),

            line_height: "22px".into(),
            line_height_small: "22px".into(),
            line_height_medium: "22px".into(),
            line_height_large: "23px".into(),
            line_height_huge: "24px".into(),

            border_radius: "3px".into(),
            border_radius_small: "2px".into(),
            border_radius_large: "8px".into(),
        }
    }
}

impl ThemeMethod for CommonTheme {
    fn light() -> Self {
        Self {
            font_color: "#11181c".into(),
            background_color: "#fff".into(),
            color_scheme: "light".into(),
            color_primary: "#0078ff".into(),
            color_primary_hover: "#2994ff".into(),
            color_primary_active: "#005ed9".into(),
            color_success: "#18a058".into(),
            color_success_hover: "#36ad6a".into(),
            color_success_active: "#0c7a43".into(),
            color_warning: "#f0a020".into(),
            color_warning_hover: "#fcb040".into(),
            color_warning_active: "#c97c10".into(),
            color_error: "#d03050".into(),
            color_error_hover: "#de576d".into(),
            color_error_active: "#ab1f3f".into(),
            border_color: "#e5e8eb".into(),
            color_neutral_background_1: "#fff".into(),
            color_neutral_background_1_hover: "#f5f5f5".into(),
            color_neutral_background_1_pressed: "#e0e0e0".into(),
            color_neutral_foreground_1: "#242424".into(),
            color_neutral_foreground_1_hover: "#242424".into(),
            color_neutral_foreground_1_pressed: "#242424".into(),
            color_neutral_foreground_2: "#424242".into(),
            color_neutral_foreground_2_hover: "#242424".into(),
            color_neutral_foreground_2_pressed: "#242424".into(),
            color_neutral_foreground_2_brand_hover: "#0f6cbd".into(),
            color_neutral_foreground_2_brand_pressed: "#115ea3".into(),
            color_neutral_stroke_1: "#d1d1d1".into(),
            color_neutral_stroke_1_hover: "#c7c7c7".into(),
            color_neutral_stroke_1_pressed: "#b3b3b3".into(),
            color_brand_background: "#0f6cbd".into(),
            color_brand_background_hover: "#115ea3".into(),
            color_brand_background_pressed: "#0c3b5e".into(),
            color_subtle_background_hover: "#f5f5f5".into(),
            color_subtle_background_pressed: "#e0e0e0".into(),
            ..CommonTheme::common()
        }
    }
    fn dark() -> Self {
        Self {
            font_color: "#ecedee".into(),
            background_color: "#1a1d1e".into(),
            color_scheme: "dark".into(),
            color_primary: "#0078ff".into(),
            color_primary_hover: "#2994ff".into(),
            color_primary_active: "#005ed9".into(),
            // color_success: "#63e2b7".into(),
            // color_success_hover: "#7fe7c4".into(),
            color_success: "#18a058".into(),
            color_success_hover: "#36ad6a".into(),
            color_success_active: "#5acea7".into(),
            color_warning: "#f0a020".into(),
            color_warning_hover: "#fcb040".into(),
            color_warning_active: "#e6c260".into(),
            color_error: "#d03050".into(),
            color_error_hover: "#de576d".into(),
            color_error_active: "#e57272".into(),
            border_color: "#1f2537".into(),
            color_neutral_background_1: "#292929".into(),
            color_neutral_background_1_hover: "#3d3d3d".into(),
            color_neutral_background_1_pressed: "#1f1f1f".into(),
            color_neutral_foreground_1: "#fff".into(),
            color_neutral_foreground_1_hover: "#fff".into(),
            color_neutral_foreground_1_pressed: "#fff".into(),
            color_neutral_foreground_2: "#d6d6d6".into(),
            color_neutral_foreground_2_hover: "#fff".into(),
            color_neutral_foreground_2_pressed: "#fff".into(),
            color_neutral_foreground_2_brand_hover: "#479ef5".into(),
            color_neutral_foreground_2_brand_pressed: "#2886de".into(),
            color_neutral_stroke_1: "#666666".into(),
            color_neutral_stroke_1_hover: "#757575".into(),
            color_neutral_stroke_1_pressed: "#6b6b6b".into(),
            color_brand_background: "#115ea3".into(),
            color_brand_background_hover: "#0f6cbd".into(),
            color_brand_background_pressed: "#0c3b5e".into(),
            color_subtle_background_hover: "#383838".into(),
            color_subtle_background_pressed: "#2e2e2e".into(),
            ..CommonTheme::common()
        }
    }
}
