[build]
target = "index.html"
# public_url = "/thaw/"
# release = true
# filehash = false

[watch]
watch = ["../thaw", "./src", "../demo_markdown"]

[serve]
address = "127.0.0.1"
port = 6421
open = false
